IF OBJECT_ID('MENU', 'U') IS NOT NULL
    DROP TABLE MENU;
    
CREATE TABLE MENU
(
    MenuID      INT PRIMARY KEY IDENTITY (1, 1),
    Name        NVARCHAR(50)   NOT NULL,
    Description NVARCHAR(255)  NOT NULL,
    Price       DECIMAL(10, 2) NOT NULL CHECK (Price >= 0) -- Price cannot be negative and must be a decimal number with 2 decimal places (e.g., 10.00)
)

IF OBJECT_ID('INGREDIENTS', 'U') IS NOT NULL
    DROP TABLE INGREDIENTS;
    
CREATE TABLE INGREDIENTS
(
    IngredientID INT PRIMARY KEY IDENTITY (1, 1),
    Name         NVARCHAR(50)   NOT NULL,
    Cost         DECIMAL(10, 2) NOT NULL CHECK (Cost >= 0),
    Supplier     NVARCHAR(50)   NOT NULL  
)

IF OBJECT_ID('MENU_INGREDIENTS', 'U') IS NOT NULL
    DROP TABLE MENU_INGREDIENTS;
    
CREATE TABLE MENU_INGREDIENTS
(
    MenuID       INT REFERENCES MENU(MenuID) ON DELETE CASCADE ON UPDATE CASCADE,
    IngredientID INT REFERENCES INGREDIENTS(IngredientID) ON DELETE CASCADE ON UPDATE CASCADE,
    PRIMARY KEY (MenuID, IngredientID),
);

IF OBJECT_ID('ALL_STAFF', 'U') IS NOT NULL
    DROP TABLE ALL_STAFF;
    
CREATE TABLE ALL_STAFF
(
    StaffID     INT PRIMARY KEY IDENTITY (1, 1),
    FullName    NVARCHAR(100)  NOT NULL,
    PhoneNumber NVARCHAR(15)   NOT NULL,
    Position    NVARCHAR(50)   NOT NULL,
    Salary      DECIMAL(10, 2) NOT NULL
);

IF OBJECT_ID('SERVING_STAFF', 'U') IS NOT NULL
    DROP TABLE SERVING_STAFF;
    
CREATE TABLE SERVING_STAFF
(
    ServingStaffID INT PRIMARY KEY IDENTITY (1, 1),
    StaffID        INT REFERENCES ALL_STAFF (StaffID) ON DELETE CASCADE ON UPDATE CASCADE
);

IF OBJECT_ID('TABLES', 'U') IS NOT NULL
    DROP TABLE TABLES;
    
CREATE TABLE TABLES
(
    TableID INT PRIMARY KEY IDENTITY (1, 1),
    Capacity INT NOT NULL
);

IF OBJECT_ID('ORDERS', 'U') IS NOT NULL
    DROP TABLE ORDERS;
    
CREATE TABLE ORDERS
(
    OrderID            INT PRIMARY KEY IDENTITY (1, 1),
    TableID            INT            NOT NULL REFERENCES TABLES (TableID) ON DELETE CASCADE ON UPDATE CASCADE,
    ServingStaffID     INT            NOT NULL REFERENCES SERVING_STAFF (ServingStaffID) ON DELETE CASCADE ON UPDATE CASCADE,
    TotalAmount        DECIMAL(10, 2) NOT NULL CHECK (TotalAmount > 0),
    TotalAmountWithTax AS (TotalAmount * 1.09) PERSISTED,
    OrderDate          DATETIME       NOT NULL DEFAULT GETDATE(),
    IsClosed           BIT            NULL
);

IF OBJECT_ID('ORDERS_MENU', 'U') IS NOT NULL
    DROP TABLE ORDERS_MENU;
    
CREATE TABLE ORDERS_MENU
(
    OrderID  INT NOT NULL REFERENCES ORDERS (OrderID) ON DELETE CASCADE ON UPDATE CASCADE,
    MenuID   INT NOT NULL REFERENCES MENU (MenuID) ON DELETE CASCADE ON UPDATE CASCADE,
    Quantity INT NOT NULL,
    PRIMARY KEY (MenuID, OrderID)
);